name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.2,name=iPhone 11 Pro Max']

    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      run: xcodebuild clean test -project LandMarks.xcodeproj -scheme LandMarks -destination "${destination}" CODE_SIGN_IDENTIFY="" CODE_SIGNING_REQUIRED=NO ONLY_ARCH=NO
      env:
        destination: ${{ matrix.destination }} 
