name: Build

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: xcodebuild -project LandMarks.xcodeproj/ -scheme LandMarks -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15"
